"""add invite_code to families

Revision ID: d30d5676eb30
Revises: 4e927e5d95d0
Create Date: 2026-07-16 23:06:21.886204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd30d5676eb30'
down_revision: Union[str, Sequence[str], None] = '4e927e5d95d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_families_invite_code'), 'families', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_families_invite_code'), table_name='families')
    op.drop_column('families', 'invite_code')
    # ### end Alembic commands ###
